#RNS-t vagy DNS-t ír át.
def transcribe(sequence, is_dna=True):
    transcribed_sequence = ''
    for nucleotide in sequence: 
        if is_dna:
            if nucleotide == "T":
                transcribed_base = "U"
            else:
                transcribed_base = nucleotide
  
        else:
            if nucleotide == "U":
                transcribed_base = "T"
            else:
                transcribed_base = nucleotide
        transcribed_sequence += transcribed_base
    print (transcribed_sequence)
    return transcribed_sequence

sequence = 'ACCGTCCTAGAGCTTTATTTGGGTCGCATCGTGCCTTTAGCCACTCTATGCTCAGGTCGGTAATGCTACAACCACTATCCGATACGTCGTTTGCAACTGGCAGGCTCTTTGTTTACTTCATTTTAGCTCCAGAATACTGGGTGCGTTCTAACCTTTCAATCATTCTTACGCACAGCACACGCAGGTTGGCTAGGCACCGATTGAAATTTCCTTCATCTGTCTGGTGCTCGCTGCGCAGCGCACTGAAGAGCTATTATAGCTACATCGGCTAACCTCAGTATGCGCTTCCCCAGCTATGAATGCATTTGTCCTCGCGCACATAGATCCAGAGTCCAACGTCAGTTCCATTGTCAACAGAGCCGTAAGTCCTCAACGAACACCCGTTCTTACAATCGGCAGGGCAATCTCGGGTTCGCCGTTTTGACGTCGAGCGCAGTAATTTATACCACGGCATTTTATTGAATATCATTAATCTCCTTTGAGCCAGTGCTCAACATGACCTCCAAGATATGGCCGAGCCGCGTGCTATGTGGACCCAGATAGCTGATGTGTCTAAAATCATTTTCCTGTGCGAAGCCCCTTATGAGTCCAACACCTGTGTGTGGACCCCTTCGCTTGGCGGTGTGCTTGAACTCAGGATCGTAGCGGTCCGCAGAGGAAGTGATAGGGTAATGCAATATACTAAAGGTGTTATTAGACTAAAGGATACAACCATGGTGGGTTAACGGGTGTCACTACAGTATGGCGCCGGGCGCAAAGATGCTTGCGTAGGGAACCTAGTAATCCTAGTCTCCTTGTAATTTATGTGACCCCTTACCGGTACGCCCACAGCTCTGTGCCCGCATACGTAGATCGGGCCACGTGACGTAGACTGGGAAATGACGTGTACTGAATAATTCCATAACGTCGGCTAGGCTATTTGGGTGCCTTTTTATCATGCCTC'
transcribe(sequence, is_dna=True)